//v.3.6 build 130619

/*
Copyright Dinamenta, UAB http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms or get Professional edition of the component please contact us at sales@dhtmlx.com
*/
dhtmlXForm.prototype.items.combo={render:function(a,b){a._type="combo";a._enabled=!0;a._value=null;a._newValue=null;this.doAddLabel(a,b);this.doAddInput(a,b,"SELECT",null,!0,!0,"dhxform_select");this.doAttachEvents(a);this.doLoadOpts(a,b);a.onselectstart=function(a){a=a||event;return a.returnValue=!0};a.childNodes[a._ll?1:0].childNodes[0].setAttribute("opt_type",b.comboType||"");a._combo=new dhtmlXComboFromSelect(a.childNodes[a._ll?1:0].childNodes[0]);a._combo._currentComboValue=a._combo.getSelectedValue();
a._combo.DOMelem_input.id=b.uid;a._combo.DOMelem_button.onmousedown=function(){return!1};b.connector&&this.doLoadOptsConnector(a,b.connector);b.filtering&&a._combo.enableFilteringMode(!0);b.readonly==!0&&this.setReadonly(a,!0);b.style&&(a._combo.DOMelem_input.style.cssText+=b.style);typeof window.addEventListener=="function"?(a._combo.DOMelem_input.addEventListener("focus",this._comboFocus,!1),a._combo.DOMelem_input.addEventListener("blur",this._comboBlur,!1)):(a._combo.DOMelem_input.attachEvent("onfocus",
this._comboFocus),a._combo.DOMelem_input.attachEvent("onblur",this._comboBlur));return this},destruct:function(a){a.childNodes[a._ll?1:0].childNodes[0].onchange=null;typeof window.addEventListener=="function"?(a._combo.DOMelem_input.removeEventListener("focus",this._comboFocus,!1),a._combo.DOMelem_input.removeEventListener("blur",this._comboBlur,!1)):(a._combo.DOMelem_input.detachEvent("onfocus",this._comboFocus),a._combo.DOMelem_input.detachEvent("onblur",this._comboBlur));a._combo._currentComboValue=
null;a._combo.destructor();a._combo=null;a._apiChange=null;this.d2(a);a=null},doAttachEvents:function(a){var b=this;a.childNodes[a._ll?1:0].childNodes[0].onchange=function(){b.doOnChange(this);b.doValidate(this.DOMParent.parentNode.parentNode)}},doValidate:function(a){a.getForm().hot_validate&&this._validate(a)},doOnChange:function(a){var b=a.DOMParent.parentNode.parentNode;if(!b._apiChange){a._newComboValue=a.getSelectedValue();if(a._newComboValue!=a._currentComboValue){if(b.checkEvent("onBeforeChange")&&
b.callEvent("onBeforeChange",[b._idd,a._currentComboValue,a._newComboValue])!==!0)return window.setTimeout(function(){a.setComboValue(a._currentComboValue)},1),!1;a._currentComboValue=a._newComboValue;b.callEvent("onChange",[b._idd,a._currentComboValue])}b._autoCheck(b._enabled)}},doLoadOptsConnector:function(a,b){var c=this,d=a;a._connector_working=!0;a._apiChange=!0;a._combo.loadXML(b,function(){d.callEvent("onOptionsLoaded",[d._idd]);d._connector_working=!1;if(d._connector_value!=null)c.setValue(d,
d._connector_value),d._connector_value=null;d._apiChange=!1;c=d=null})},enable:function(a){if(String(a.className).search("disabled")>=0)a.className=String(a.className).replace(/disabled/gi,"");a._enabled=!0;a._combo.disable(!1);a._combo.DOMelem_button.src=(window.dhx_globalImgPath?dhx_globalImgPath:"")+"combo_select"+(dhtmlx.skin?"_"+dhtmlx.skin:"")+".gif"},disable:function(a){String(a.className).search("disabled")<0&&(a.className+=" disabled");a._enabled=!1;a._combo.disable(!0);a._combo.DOMelem_button.src=
(window.dhx_globalImgPath?dhx_globalImgPath:"")+"combo_select_dis"+(dhtmlx.skin?"_"+dhtmlx.skin:"")+".gif"},getCombo:function(a){return a._combo},setValue:function(a,b){a._connector_working?a._connector_value=b:(a._apiChange=!0,a._combo.setComboValue(b),a._combo._currentComboValue=a._combo.getActualValue(),a._apiChange=!1)},getValue:function(a){return a._combo.getActualValue()},setWidth:function(a,b){a.childNodes[a._ll?1:0].childNodes[0].style.width=b+"px"},setReadonly:function(a,b){if(a._combo)a._combo_ro=
b,a._combo.readonly(a._combo_ro)},isReadonly:function(a){return a._combo_ro||!1},setFocus:function(a){a._enabled&&a._combo.DOMelem_input.focus()},_setCss:function(a,b,c){a._combo.DOMlist.style.fontSize=c},_comboFocus:function(a){var a=a||event,b=(a.target||a.srcElement).parentNode.parentNode,c=b.parentNode.parentNode;c.getForm().skin=="dhx_terrace"&&b.className.search(/combo_in_focus/)<0&&(b.className+=" combo_in_focus");for(var d=0;d<c._combo.DOMlist.childNodes.length;d++)c._combo.DOMlist.childNodes[d].onmousedown=
function(){return!1};c.callEvent("onFocus",[c._idd]);c=b=null},_comboBlur:function(a){var a=a||event,b=(a.target||a.srcElement).parentNode.parentNode,c=b.parentNode.parentNode;if(c.getForm().skin=="dhx_terrace"&&b.className.search(/combo_in_focus/)>=0)b.className=b.className.replace(/combo_in_focus/gi,"");for(var d=0;d<c._combo.DOMlist.childNodes.length;d++)c._combo.DOMlist.childNodes[d].onmousedown=null;c.callEvent("onBlur",[c._idd]);c=b=null}};
(function(){for(var a in{doAddLabel:1,doAddInput:1,doLoadOpts:1,doUnloadNestedLists:1,setText:1,getText:1,isEnabled:1,_checkNoteWidth:1})dhtmlXForm.prototype.items.combo[a]=dhtmlXForm.prototype.items.select[a]})();dhtmlXForm.prototype.items.combo.d2=dhtmlXForm.prototype.items.select.destruct;dhtmlXForm.prototype.getCombo=function(a){return this.doWithItem(a,"getCombo")};

//v.3.6 build 130619

/*
CopyrigDinamenta, UABTD. http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms or get Professional edition of the component please contact us at sales@dhtmlx.com
*/